//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlihososinhvien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocphi
    {
        public string Khoi { get; set; }
        public string Nam { get; set; }
        public Nullable<double> Hocphi1 { get; set; }
    }
}
