//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlihososinhvien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLMNEntities : DbContext
    {
        public QLMNEntities()
            : base("name=QLMNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hocphi> Hocphis { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thongtintre> Thongtintres { get; set; }
        public virtual DbSet<Thucdon> Thucdons { get; set; }
    
        public virtual ObjectResult<allhocphi_Result> allhocphi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allhocphi_Result>("allhocphi");
        }
    
        public virtual ObjectResult<allkhoa_Result> allkhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allkhoa_Result>("allkhoa");
        }
    
        public virtual ObjectResult<allthucdon_Result> allthucdon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allthucdon_Result>("allthucdon");
        }
    
        public virtual ObjectResult<alltre_Result> alltre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<alltre_Result>("alltre");
        }
    
        public virtual ObjectResult<capnhattttre_Result> capnhattttre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<capnhattttre_Result>("capnhattttre");
        }
    
        public virtual int deleteKhoi(string lopp)
        {
            var loppParameter = lopp != null ?
                new ObjectParameter("lopp", lopp) :
                new ObjectParameter("lopp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteKhoi", loppParameter);
        }
    
        public virtual int Deletettre(string matrep)
        {
            var matrepParameter = matrep != null ?
                new ObjectParameter("Matrep", matrep) :
                new ObjectParameter("Matrep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Deletettre", matrepParameter);
        }
    
        public virtual ObjectResult<string> getallkhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getallkhoa");
        }
    
        public virtual ObjectResult<string> getalllop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getalllop");
        }
    
        public virtual ObjectResult<string> getalltre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getalltre");
        }
    
        public virtual int insertkhoi(string lopp, string khoap)
        {
            var loppParameter = lopp != null ?
                new ObjectParameter("lopp", lopp) :
                new ObjectParameter("lopp", typeof(string));
    
            var khoapParameter = khoap != null ?
                new ObjectParameter("khoap", khoap) :
                new ObjectParameter("khoap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertkhoi", loppParameter, khoapParameter);
        }
    
        public virtual int Inserttre(string masvp, string hosvp, string tensvp, Nullable<System.DateTime> ngaysinhp, string gioitinhp, string lop, string diachip, string dantocp, string tongiaop)
        {
            var masvpParameter = masvp != null ?
                new ObjectParameter("masvp", masvp) :
                new ObjectParameter("masvp", typeof(string));
    
            var hosvpParameter = hosvp != null ?
                new ObjectParameter("hosvp", hosvp) :
                new ObjectParameter("hosvp", typeof(string));
    
            var tensvpParameter = tensvp != null ?
                new ObjectParameter("tensvp", tensvp) :
                new ObjectParameter("tensvp", typeof(string));
    
            var ngaysinhpParameter = ngaysinhp.HasValue ?
                new ObjectParameter("ngaysinhp", ngaysinhp) :
                new ObjectParameter("ngaysinhp", typeof(System.DateTime));
    
            var gioitinhpParameter = gioitinhp != null ?
                new ObjectParameter("gioitinhp", gioitinhp) :
                new ObjectParameter("gioitinhp", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(string));
    
            var diachipParameter = diachip != null ?
                new ObjectParameter("diachip", diachip) :
                new ObjectParameter("diachip", typeof(string));
    
            var dantocpParameter = dantocp != null ?
                new ObjectParameter("dantocp", dantocp) :
                new ObjectParameter("dantocp", typeof(string));
    
            var tongiaopParameter = tongiaop != null ?
                new ObjectParameter("tongiaop", tongiaop) :
                new ObjectParameter("tongiaop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Inserttre", masvpParameter, hosvpParameter, tensvpParameter, ngaysinhpParameter, gioitinhpParameter, lopParameter, diachipParameter, dantocpParameter, tongiaopParameter);
        }
    
        public virtual ObjectResult<timkiemtttre_Result> timkiemtttre(string masvp, string hosvp, string tensvp, string gioitinhp, string diachip)
        {
            var masvpParameter = masvp != null ?
                new ObjectParameter("masvp", masvp) :
                new ObjectParameter("masvp", typeof(string));
    
            var hosvpParameter = hosvp != null ?
                new ObjectParameter("hosvp", hosvp) :
                new ObjectParameter("hosvp", typeof(string));
    
            var tensvpParameter = tensvp != null ?
                new ObjectParameter("tensvp", tensvp) :
                new ObjectParameter("tensvp", typeof(string));
    
            var gioitinhpParameter = gioitinhp != null ?
                new ObjectParameter("gioitinhp", gioitinhp) :
                new ObjectParameter("gioitinhp", typeof(string));
    
            var diachipParameter = diachip != null ?
                new ObjectParameter("diachip", diachip) :
                new ObjectParameter("diachip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiemtttre_Result>("timkiemtttre", masvpParameter, hosvpParameter, tensvpParameter, gioitinhpParameter, diachipParameter);
        }
    
        public virtual int updatekhoi(string lopp, string khoap)
        {
            var loppParameter = lopp != null ?
                new ObjectParameter("lopp", lopp) :
                new ObjectParameter("lopp", typeof(string));
    
            var khoapParameter = khoap != null ?
                new ObjectParameter("khoap", khoap) :
                new ObjectParameter("khoap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatekhoi", loppParameter, khoapParameter);
        }
    
        public virtual int Updatetre(string masvp, string hosvp, string tensvp, Nullable<System.DateTime> ngaysinhp, string gioitinhp, string lop, string diachip, string dantocp, string tongiaop)
        {
            var masvpParameter = masvp != null ?
                new ObjectParameter("masvp", masvp) :
                new ObjectParameter("masvp", typeof(string));
    
            var hosvpParameter = hosvp != null ?
                new ObjectParameter("hosvp", hosvp) :
                new ObjectParameter("hosvp", typeof(string));
    
            var tensvpParameter = tensvp != null ?
                new ObjectParameter("tensvp", tensvp) :
                new ObjectParameter("tensvp", typeof(string));
    
            var ngaysinhpParameter = ngaysinhp.HasValue ?
                new ObjectParameter("ngaysinhp", ngaysinhp) :
                new ObjectParameter("ngaysinhp", typeof(System.DateTime));
    
            var gioitinhpParameter = gioitinhp != null ?
                new ObjectParameter("gioitinhp", gioitinhp) :
                new ObjectParameter("gioitinhp", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(string));
    
            var diachipParameter = diachip != null ?
                new ObjectParameter("diachip", diachip) :
                new ObjectParameter("diachip", typeof(string));
    
            var dantocpParameter = dantocp != null ?
                new ObjectParameter("dantocp", dantocp) :
                new ObjectParameter("dantocp", typeof(string));
    
            var tongiaopParameter = tongiaop != null ?
                new ObjectParameter("tongiaop", tongiaop) :
                new ObjectParameter("tongiaop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updatetre", masvpParameter, hosvpParameter, tensvpParameter, ngaysinhpParameter, gioitinhpParameter, lopParameter, diachipParameter, dantocpParameter, tongiaopParameter);
        }
    
        public virtual int inserthocphi(string khoip, string namp, Nullable<double> hocphip)
        {
            var khoipParameter = khoip != null ?
                new ObjectParameter("khoip", khoip) :
                new ObjectParameter("khoip", typeof(string));
    
            var nampParameter = namp != null ?
                new ObjectParameter("namp", namp) :
                new ObjectParameter("namp", typeof(string));
    
            var hocphipParameter = hocphip.HasValue ?
                new ObjectParameter("hocphip", hocphip) :
                new ObjectParameter("hocphip", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserthocphi", khoipParameter, nampParameter, hocphipParameter);
        }
    
        public virtual int updatehocphi(string khoip, string namp, Nullable<double> hocphip)
        {
            var khoipParameter = khoip != null ?
                new ObjectParameter("khoip", khoip) :
                new ObjectParameter("khoip", typeof(string));
    
            var nampParameter = namp != null ?
                new ObjectParameter("namp", namp) :
                new ObjectParameter("namp", typeof(string));
    
            var hocphipParameter = hocphip.HasValue ?
                new ObjectParameter("hocphip", hocphip) :
                new ObjectParameter("hocphip", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatehocphi", khoipParameter, nampParameter, hocphipParameter);
        }
    
        public virtual ObjectResult<string> timkimthucdon(string thup)
        {
            var thupParameter = thup != null ?
                new ObjectParameter("thup", thup) :
                new ObjectParameter("thup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("timkimthucdon", thupParameter);
        }
    }
}
