//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlihososinhvien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thucdon
    {
        public string Thu { get; set; }
        public string Bua { get; set; }
        public string ThucDon1 { get; set; }
    }
}
